export const categories = {
  'Other income': {
    name: 'Other income',
    color: '#88888b',
    type: 'income',
    visibility: true,
    limit: 0,
  },
  Salary: { name: 'Salary', color: '#4daf3c', type: 'income', visibility: true, limit: 0 },
  Cashback: { name: 'Cashback', color: '#aa25e7', type: 'income', visibility: true, limit: 0 },
  'Interest on deposits': {
    name: 'Interest on deposits',
    color: '#6966ca',
    type: 'income',
    visibility: true,
    limit: 0,
  },
  'Other expenses': {
    name: 'Other expenses',
    color: '#88888b',
    type: 'expense',
    visibility: true,
    limit: 0,
  },
  Supermarkets: {
    name: 'Supermarkets',
    color: '#f3b619',
    type: 'expense',
    visibility: true,
    limit: 0,
  },
  Utilities: { name: 'Utilities', color: '#dd446c', type: 'expense', visibility: true, limit: 0 },
  Clothes: { name: 'Clothes', color: '#058795', type: 'expense', visibility: true, limit: 0 },
  'Cafe and restaurants': {
    name: 'Cafe and restaurants',
    color: '#22a9e7',
    type: 'expense',
    visibility: true,
    limit: 0,
  },
  Travel: { name: 'Travel', color: '#e7228c', type: 'expense', visibility: true, limit: 0 },
  Rent: { name: 'Rent', color: '#4e17e3a1', type: 'expense', visibility: true, limit: 0 },
};
